get_latest command to latest

diff --git a/bin/stow-get b/bin/stow-get
--- a/bin/stow-get
+++ b/bin/stow-get
@@ -55,7 +55,7 @@ function set_default {
   script_dir=$(cd "$(dirname "$0")";pwd)
   conf_dir=("$script_dir/../share/stow-get")
   conf_file="$HOME/.stow-get"
-  default_inst_type=""
+  default_inst_type="gnu"
   force=0
   dryrun=0
   packages=()
@@ -88,6 +88,13 @@ function reset_inst_val {
   function make_cmd {
     make all && make install
   }
+  function get_latest {
+    if [ "$inst_type" = "gnu" ];then
+      get_gnu_latest "$@" 1
+    else
+      err "get_latest is undefined for $inst_type"
+    fi
+  }
 }
 reset_inst_val
 # }}}
@@ -109,17 +116,17 @@ Sub commands:
    list           List up installed packages.
    packages       List up available packages which have configuration files.
    info <package> Show configuration file of package.
-   get_latest  <package>
-                  Show the latest version of package (only for GNU packages).
+   latest <package>
+                  Show the latest version of package.
    version        Show version.
    help           Show this help.
 
 Arguments:
    -c <conf file> Configuration file (default: $conf_file).
-   -d <conf dir>  Additional directory of package configuration files (default: ${conf_dir[@]}).
+   -d <conf dir>  Additional directory of package configuration files (default: ${conf_dir[*]}).
                   Multi directories can be specified by separating with \",\".
    -i <inst dir>  Directory to install packages (default: $inst_dir).
-   -t <inst type> Set install type: only for install with package name (default: $default_inst_type).
+   -t <inst type> Set install type (default: $default_inst_type).
    -f             Force to re-install.
    -D             Dry run mode.
    -V             Verbose mode.
@@ -131,6 +138,10 @@ See more details at: https://github.com/rcmdnk/stow-get
   if [ "$ret" != "" ];then
     exit "$ret"
   fi
+} ## }}}
+
+function show_version { ## {{{
+  echo "$(basename "$0") $STOW_GET_VERSION $STOW_GET_DATE"
 } ## }}}
 
 function banner { ## {{{
@@ -169,9 +180,9 @@ function cd_check { ## {{{
   return $ret
 } ## }}}
 
-function get_pac_conf { # {{{
+function get_pac_conf { ## {{{
   conf_name="${1}.sh"
-  is_exit="${2:-1}"
+  is_exit="${2:-0}"
   pac_conf=""
   for d in "${conf_dir[@]}";do
     if [ -f "${d}/${conf_name}" ];then
@@ -179,32 +190,34 @@ function get_pac_conf { # {{{
       break
     fi
   done
-  if [ "$pac_conf" = "" ] && [ "$is_exit" -eq 1 ];then
-    err "No configuration file for $1 is found."
-    exit $EXIT_NO_PAC_CONF
+  if [ "$pac_conf" = "" ];then
+    warn "No configuration file for $1 is found."
+    if [ "$is_exit" -eq 1 ];then
+      exit $EXIT_NO_PAC_CONF
+    fi
   fi
-} # }}}
+  if [ "$inst_type" = "" ];then
+    warn "No inst_type is given. Trying to $default_inst_type type installation."
+    inst_type=$default_inst_type
+  fi
+} ## }}}
 
-function source_pac_conf { # {{{
+function source_pac_conf { ## {{{
   reset_inst_val
-  is_exit=1
-  if [ "$default_inst_type" != "" ];then
-    inst_type="$default_inst_type"
-    is_exit=0
-  fi
-  get_pac_conf "$package" "$is_exit"
+  get_pac_conf "$package"
   if [ "$pac_conf" != "" ];then
     source "$pac_conf"
   fi
   set_target
-} # }}}
+} ## }}}
 
 function set_version { # {{{
   if [ "$version" = "" ] || [ "$version" = "latest" ];then
-    if [ "$inst_type" = "gnu" ];then
-      get_gnu_latest "$package"
-    else
+    get_latest "$package"
+    ret=$?
+    if [ $ret -ne 0 ];then
       err "version(=$version) is not recognized for $package."
+      err "Set version or get_latest function."
       exit $EXIT_NO_VERSION
     fi
   fi
@@ -344,7 +357,9 @@ function stow_install_github_direct { ## {{{
 function stow_install_wrapper { ## {{{
   cd_check "$TMP_DIR"
 
-  if [ "$inst_type" = "tarball" ];then
+  if type -a "stow_install" >/dev/null 2>&1;then
+    stow_install
+  elif [ "$inst_type" = "tarball" ];then
     stow_install_tarball
   elif [ "$inst_type" = "gnu" ];then
     stow_install_gnu
@@ -352,15 +367,9 @@ function stow_install_wrapper { ## {{{
     stow_install_github
   elif [ "$inst_type" = "github_direct" ];then
     stow_install_github_direct
-  elif [ "$inst_type" != "" ];then
-    err "Invalid inst_type: $inst_type"
-    return 1
   else
-    if ! eval type -a stow_install > /dev/null 2>&1;then
-      err "Neither type nor stow_install is not defined for $package."
-      return 1
-    fi
-    stow_install
+    err "Invalid inst_type: $inst_type, and stow_install function is not set."
+    return 1
   fi
 } ## }}}
 
@@ -368,13 +377,13 @@ function stow_install_wrapper { ## {{{
 
 # Check argumetns {{{
 
-COMMANDS=(install rm remove uninstall list packages info get_latest version help)
-NEED_ARGS=(uninstall info get_latest)
+COMMANDS=(install rm remove uninstall list packages info latest version help)
+NEED_ARGS=(uninstall info latest)
 
 if [ "$#" -eq 0 ] || [ "$1" = "help" ] || [ "$1" = "-h" ];then
   show_help 0
 elif [ "$1" = "version" ] || [ "$1" = "-v" ];then
-  echo "$(basename "$0") $STOW_GET_VERSION $STOW_GET_DATE"
+  show_version
   exit 0
 fi
 
@@ -397,7 +406,7 @@ while getopts c:d:i:t:fDVvh OPT;do
     "f" ) force=1 ;;
     "D" ) dryrun=1 ;;
     "V" ) verbose=1 ;;
-    "v" ) echo "$(basename "$0") $STOW_GET_VERSION $STOW_GET_DATE"; exit 0;;
+    "v" ) show_version; exit 0;;
     "h" ) show_help 0;;
     * ) echo "Check \"$(basename "$0") -h\" for more information" >/dev/tty;exit $EXIT_WRONG_ARG;;
 
@@ -412,10 +421,14 @@ if echo " ${NEED_ARGS[*]} "|grep -q " $command ";then
   fi
 fi
 
-if [ "$command" = "get_latest" ];then
+if [ "$command" = "latest" ];then
   packages=("$@")
   for package in "$@";do
-    get_gnu_latest "$package" 1
+    get_pac_conf "$package" 0 2>/dev/null
+    if [ "$pac_conf" != "" ];then
+      source "$pac_conf"
+    fi
+    get_latest "$package"
   done
   exit
 fi
@@ -457,7 +470,7 @@ if [ "$command" = "packages" ];then
 fi
 # }}}
 
-# Check PATH/LD_LIBRARY_PATH
+# Check PATH/LD_LIBRARY_PATH {{{
 if ! echo "$PATH"| grep -q "$inst_dir/bin";then
   warn "PATH doesn't include $inst_dir/bin,
 which may make a problem to search dependencies or to use stow command."
@@ -466,6 +479,7 @@ if ! echo "$LD_LIBRARY_PATH"| grep -q "$inst_dir/lib";then
   warn "LD_LIBRARY_PATH doesn't include $inst_dir/lib,
 which may make a problem to search dependencies."
 fi
+# }}}
 
 # Check necessary packages {{{
 necessary_packages=(unzip wget stow)
